analytics:
  google: UA-68662001-1
color:
  brandColors:
    - '#FDFFFE'
    - '#84946D'
    - '#595651'
    - '#3A3633'
    - '#CCAB98'
  brandStrength: 0.884046
  lightness: 0.090461
  rhythmicContrast: 0.895559
  saturation: 0.912007
cta: {}
layout_spectrum: 0.794408
name: 'Sitecore Collection '
opengraph: {}
purpose: []
typography_spectrum: 0.063322
