typography_spectrum: 0.24765559704974294
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.1543604175094515
  lightness: 0.14125088206492364
  saturation: 0.7909759511239827
  rhythmicContrast: 0.22522167954593897
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.794408
analytics:
  google: UA-68662001-1
  facebook: null
  twitter: null
name: 'Sitecore Collection '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Sample link to Velir
    url: 'http://www.velir.com'
    type: external
favicon: null
title: 'This is my headline. There are many like it, but this one is mine.'
description: This is a sample tagline. I suppose it could even be interesting.
purpose: []
