typography_spectrum: 0.063322
color:
  brandColors:
    - '#ffffff'
    - '#fac443'
    - '#e84646'
    - '#43c35e'
    - '#000000'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.794408
analytics:
  google: UA-68662001-1
  facebook: null
  twitter: null
name: 'Sitecore Collection '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Sample link to Velir
    url: 'http://www.velir.com'
    type: external
favicon: null
title: 'This is my headline. There are many like it, but this one is mine.'
description: This is a sample tagline. I suppose it could even be interesting.
purpose: []
