name: 'Sitecore Collection '
favicon: null
layout_spectrum: 0.794408
typography_spectrum: 0.063322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68662001-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fac443'
    - '#e84646'
    - '#43c35e'
    - '#000000'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
