analytics:
  google: UA-68662001-1
color:
  brandColors:
    - '#000000'
    - '#281000'
    - '#888068'
    - '#B04838'
    - '#F8A070'
  brandStrength: 1
  lightness: 0.6875
  rhythmicContrast: 0.630756
  saturation: 0.622532
cta: {}
layout_spectrum: 0.679276
name: Sitecore Collection
opengraph: {}
purpose: []
typography_spectrum: 0.62837
