name: Sitecore Collection
favicon: null
layout_spectrum: 0.608552
typography_spectrum: 0.62837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68662001-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#281000'
    - '#888068'
    - '#B04838'
    - '#F8A070'
  brandStrength: 0.6875
  lightness: 0.925164
  saturation: 0.272203
  rhythmicContrast: 0.825657
purpose: []
