analytics: {}
color:
  brandColors:
    - '#000000'
    - '#281000'
    - '#888068'
    - '#B04838'
    - '#F8A070'
  brandStrength: 0.6875
  lightness: 0.925164
  rhythmicContrast: 0.825657
  saturation: 0.272203
cta: {}
layout_spectrum: 0.608552
name: Sitecore Collection
opengraph: {}
purpose: []
typography_spectrum: 0.5701
